### ISSUE TITLE
Error in building lib

### ISSUE THREAD

**Issue by ibroheem** [huntlabs/hunt-net#4]
/.../..../hunt/collection/AbstractMap.d(485,5): Error: undefined identifier `CloneMemberTemplate`
/.../..../hunt/collection/AbstractMap.d(485,5): Error: mixin `hunt.collection.AbstractMap.AbstractMap!(Worker, Object).AbstractMap.CloneMemberTemplate!(typeof(this))` is not defined
/.../..../hunt/collection/HashMap.d(116,22): Error: template instance `hunt.collection.AbstractMap.AbstractMap!(Worker, Object)` error instantiating
/.../..../hunt/collection/HashSet.d(84,15):        instantiated from here: `HashMap!(Worker, Object)`
/.../..../hunt/concurrency/ThreadPoolExecutor.d(421,13):        instantiated from here: `HashSet!(Worker)`
/.../..../hunt/collection/HashMap.d(414,16): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.get` does not override any function
/.../..../hunt/collection/HashMap.d(463,19): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.containsKey` does not override any function
/.../..../hunt/collection/HashMap.d(479,16): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.put` does not override any function
/.../..../hunt/collection/HashMap.d(680,16): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.remove` does not override any function
/.../..../hunt/collection/HashMap.d(743,19): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.clear` does not override any function
/.../..../hunt/collection/HashMap.d(761,19): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.containsValue` does not override any function
/.../..../hunt/collection/HashMap.d(784,5): Error: undefined identifier `CloneMemberTemplate`
/.../..../hunt/collection/HashMap.d(784,5): Error: mixin `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.CloneMemberTemplate!(typeof(this), TopLevel.no, (typeof(this) from, typeof(this) to)
{
to.reinitialize();
to.putMapEntries(from, false);
}
)` is not defined
/.../..../hunt/collection/HashMap.d(792,18): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.opApply` does not override any function
/.../..../hunt/collection/HashMap.d(814,18): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.opApply` does not override any function
/.../..../hunt/collection/HashMap.d(853,27): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.byKey` does not override any function
/.../..../hunt/collection/HashMap.d(857,27): Error: function `hunt.collection.HashMap.HashMap!(Worker, Object).HashMap.byValue` does not override any function
/.../..../hunt/collection/HashMap.d(1034,5): Error: template instance `hunt.collection.HashMap.TreeNode!(Worker, Object)` error instantiating

**Comment by ibroheem** [comment]
DMD64 D Compiler v2.085.0
Ubuntu 19.04

LDC got its own set of issues also.

**Comment by Heromyth** [comment]
You need upgrade your compiler to DMD 2.088+.
